version: "2"

services:
  conda-store-build:
    build: .
    volumes:
      - ./tests/assets/environments:/opt/environments:ro
      - ./mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'build', '-p', '/opt/environments', '-o', '/opt/mount/environments', '-s', '/opt/mount/store', '--uid', '1000', '--gid', '100', '--permissions', '775', '--storage-backend', 's3']
    environment:
      TZ: America/New_York
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  conda-store-ui:
    build: .
    volumes:
      - ./mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'ui', '-s', '/opt/mount/store', '--port', '5000']
    ports:
      - "5000:5000"
    environment:
      TZ: America/New_York
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
   
  conda-store-api:
    build: .
    volumes:
      - ./mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'api', '-s', '/opt/mount/store', '--port', '5001']
    ports:
      - "5001:5001"
    environment:
      TZ: America/New_York
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    
  conda-store-registry:
    build: .
    volumes:
      - ./mount:/opt/mount
    command: ['python', '-m', 'conda_store', 'registry', '-s', '/opt/mount/store', '--port', '5002', '--storage-backend', 's3']
    ports:
      - "5002:5002"
    environment:
      TZ: America/New_York
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      PATH: "/opt/conda/envs/conda-store/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    command: server /var/lib/minio
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key

